[general]
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[font]
size = 12.0

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[window]
padding = { x = 14, y = 12 }

[scrolling]
multiplier = 3
